# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  - "pull_request"
  - "push"

jobs:

  continuous-integration:
    name: "Continuous Integration"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"

        dependencies:
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@1.8.2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"

      - name: "Check out PHP documentation with git"
        run: sh update.sh
        working-directory: "generator/doc"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1.0.3"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install dependencies with composer in generator/ directory"
        run: "composer install --no-interaction"
        working-directory: "generator"

      - name: "Install dependencies with composer in root directory"
        run: "composer install --no-interaction"

      - name: "Run tests with phpunit/phpunit in generator/ directory"
        run: "vendor/bin/phpunit"
        working-directory: "generator"

      - name: "Run coding standard checks with squizlabs/php_codesniffer in generator/ directory"
        run: "composer cs-check"
        working-directory: "generator"

      - name: "Run static code analysis with phpstan/phpstan in generator/ directory"
        run: "composer phpstan"
        working-directory: "generator"

      - name: "Dump autoloader with composer in root directory"
        run: "composer dump-autoload"

      - name: "Run coding standard checks with squizlabs/php_codesniffer in root directory"
        run: "composer cs-check"

      - name: "Run static code analysis with phpstan/phpstan in root directory"
        run: "composer phpstan"

      - name: "Regenerate files"
        run: "./safe.php generate"
        working-directory: "generator"

      - name: "Check if regenerated files are different"
        run: |
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            # all is good
            echo "Generated files are the same as committed file: OK"
          else
            # Uncommitted changes
            echo "Generated files are different from commited files. Please run './safe.php generate' command and commit the results."
            echo "Detected changes:"
            git status
            git diff
            echo "Generated files are different from commited files. Please run './safe.php generate' command and commit the results."
            exit 1;
          fi
      - name: "Check if refactoring can be done with rector/rector:~0.5.0"
        run: "composer install && composer rector && composer test"
        working-directory: "generator/tests/rector/0.5"

      - name: "Check if refactoring can be done with rector/rector:~0.6.0"
        run: "composer install && composer rector && composer test"
        working-directory: "generator/tests/rector/0.6"
        if: matrix.php-version != '7.4'

      - name: "Check if refactoring can be done with rector/rector:~0.7.0"
        run: "composer install && composer rector && composer test"
        working-directory: "generator/tests/rector/0.7"

      - name: "Archive code coverage results"
        uses: "actions/upload-artifact@v1"
        with:
          name: "build"
          path: "generator/build"

      - name: "Upload test coverage to coveralls"
        continue-on-error: true
        run: "php vendor/bin/php-coveralls -v"
        working-directory: "generator"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_RUN_LOCALLY: 1
